version: "3"
services:
  frontend:
      container_name: vue
      image: ref_frontend:v1.0.0
      ports: 
        - "80:80"

  processing:
      container_name: python_processing
      image: refuel_proccesing:v1.0.0
      ports: 
        - "8000:8000"

  diary:
    container_name: diary_go
    image: diary_go:v1.0.0
    ports:
      - 8889:8889

  refuel:
    container_name: refuel_go
    image: refuel_go:v1.0.0
    ports:
      - 8888:8888
  
  # nginx_refuel:
  #   container_name: nginx_refuel
  #   image: nginx_refuel:v1.0.0
  #   restart: always
  #   ports:
  #     - 80:80
