version: "3"
services:
  diary:
    container_name: diary_vue
    build: ./VueApp/en_out_calc/
    ports:
      - 8080:8080

  nginx_diary:
    build: ./nginx/
    restart: always
    ports:
      - 80:80

  api:
    image: refuel_diary_go:latest
    restart: always
    ports: 
      - "8888:8888"

  # python-main:
  #   container_name: py-main
  #   build: .
  #   ports: 
  #     - "5000:5000"
  #   depends_on:
  #     - db
  #     - redis
  # go:
  #   image: refuel_go:v0.1
  #   restart: always
  #   ports: 
  #     - "1234:8080"
  # db:
  #   container_name: db
  #   image: postgres:12
  #   restart: always
  #   environment:
  #     - POSTGRES_DB=${DB}
  #     - POSTGRES_USER=${PSQL_USER}
  #     - POSTGRES_PASSWORD=${PSWD}
  #   ports: 
  #     - "5433:5432"

  # redis:
  #   image: redis:latest
  #   restart: always
  #   ports: 
  #     - "6379:6379"

