version: "3"
services:
  # pythonmain:
      # container_name: pythonmain
      # build: python/
      # ports: 
      #   - "5000:5000"

  diary:
    container_name: diary_vue
    build: VueApp/en_out_calc/
    ports:
      - 8080:8080

  nginx_serv:
    build: nginx/
    restart: always
    ports:
      - 80:80


  api:
    image: refuel_diary_go:latest
    restart: always
    ports: 
      - "8888:8888"

  # redis_ref:
  #   container_name: redis_ref
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - 6379:6379

  # python-main:
  #   container_name: py-main
  #   build: .
  #   ports: 
  #     - "5000:5000"
  #   depends_on:
  #     - db
  #     - redis
  # go:
  #   image: refuel_go:v0.1
  #   restart: always
  #   ports: 
  #     - "1234:8080"
