version: "3.9"
services:
  python:
    container_name: refueling
    # image: irt-t-refuel:v0.4
    build: .
    ports: 
      - "5000:5000"
    depends_on:
      - db
      - redis
  go:
    image: refuel_go:v0.1
    restart: always
    ports: 
      - "1234:8080"
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSWD}
    ports: 
      - "5433:5432"
  
  redis:
    image: redis:latest
    restart: always
    ports: 
      - "6379:6379"