version: "3"
services:
  frontend:
    container_name: vue
    image: mrzlkaaa/irt-t-refuel:v1.1.1
    ports:
      - "80:80"
      - "443:443"

  processing:
    container_name: python_processing
    image: mrzlkaaa/refuel_proccesing:v1.0.0
    ports:
      - "8890:8890"

  diary:
    container_name: diary_go
    image: mrzlkaaa/diary_go:v1.0.2
    restart: always
    ports:
      - 8889:8889

  mcu_generator:
    container_name: mcu_generator
    image: mrzlkaaa/mcu_generator:v1.0.1
    restart: always
    ports:
      - 8891:8891

  refuel:
    container_name: refuel_go
    image: mrzlkaaa/refuel_go:v1.0.0
    restart: always
    ports:
      - 8888:8888

  ref_go_api:
    container_name: ref_go_api
    image: mrzlkaaa/refuel_api:v1.0.2
    restart: always
    ports:
      - 88:88
      - 89:89
      - 8000:8000
